# -*- coding: utf-8 -*-
"""egyptian-id-ocr.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1OKg8RwOVrBzGSGqqKEriPyLqb0t5qMa6

# Model_1 To Detect objects
"""

from google.colab import drive
drive.mount('/content/drive')

!pip install roboflow
from roboflow import Roboflow
rf = Roboflow(api_key="JiN3MQkW1CkxFGPpnE0K")
project = rf.workspace("omartamer0").project("egyptian-id-detectr")
version = project.version(3)
dataset = version.download("yolov8")

!pip install ultralytics
!pip install pytesseract
!apt-get update
!apt-get install -y tesseract-ocr
!apt-get install -y tesseract-ocr-ara

!yolo task=detect mode=train model=yolov8n.pt data='/content/Egyptian-ID-Detectr-3/data.yaml' epochs=10 imgsz=640 name='train_id_detectr_v1'

from ultralytics import YOLO
import os

# First, let's list the contents of the runs/detect directory to verify the actual path
print("Listing contents of /content/runs/detect/ (after first training):")
!ls -R /content/runs/detect/

# Load the trained model from the first specific run
model = YOLO('/content/runs/detect/train_id_detectr_v1/weights/best.pt')
# Evaluate on the validation dataset
results = model.val()

# Print summary metrics
print(f"Precision: {results.box.mp:.4f}")  # Mean Precision
print(f"Recall: {results.box.mr:.4f}")     # Mean Recall
print(f"mAP@50: {results.box.map50:.4f}")  # Mean Average Precision at IoU 0.5
print(f"mAP@50-95: {results.box.map:.4f}") # Mean Average Precision at IoU 0.5:0.95

"""# hyperparameter tuning"""

!yolo task=detect model=yolov8n.pt data='/content/Egyptian-ID-Detectr-3/data.yaml' epochs=30 imgsz=640 batch=32 lr0=0.005 name='train_id_detectr_hyper'

from ultralytics import YOLO

# Load the trained model from the hyperparameter tuning run
model = YOLO('/content/runs/detect/train_id_detectr_hyper/weights/best.pt')
# Evaluate on the validation dataset
results = model.val()

# Print summary metrics
print(f"Precision: {results.box.mp:.4f}")  # Mean Precision
print(f"Recall: {results.box.mr:.4f}")     # Mean Recall
print(f"mAP@50: {results.box.map50:.4f}")  # Mean Average Precision at IoU 0.5
print(f"mAP@50-95: {results.box.map:.4f}") # Mean Average Precision at IoU 0.5:0.95

"""### Download 'Egyptian-ID-Detectr-3' dataset locally"""

# Zip the 'Egyptian-ID-Detectr-3' dataset
!zip -r /content/egyptian_id_detectr.zip /content/Egyptian-ID-Detectr-3

# Download the zipped file to your local machine
from google.colab import files
files.download('/content/egyptian_id_detectr.zip')

"""# Model_2 To Detect ID Numbers"""

!pip install roboflow # Already installed, but good for robustness

from roboflow import Roboflow
rf = Roboflow(api_key="JiN3MQkW1CkxFGPpnE0K")
project = rf.workspace("egyptian-ids").project("arabic-numbers-vmdt0")
version = project.version(2)
dataset = version.download("yolov8")
print(f"Dataset 'arabic-numbers-vmdt0-2' downloaded to: {dataset.location}")
!ls -F {dataset.location}

#train: /content/Egyptian-ID-Detectr-3/train/images
#val: /content/Egyptian-ID-Detectr-3/valid/images
!yolo task=detect mode=train model=yolov8s.pt data='/content/arabic-numbers-2/data.yaml' epochs=20 imgsz=640 name='train_arabic_numbers_v2'

from ultralytics import YOLO

# Load the trained model from the specific run
model = YOLO('/content/runs/detect/train_arabic_numbers_v2/weights/best.pt')
# Evaluate on the validation dataset
results = model.val()

# Print summary metrics
print(f"Precision: {results.box.mp:.4f}")  # Mean Precision
print(f"Recall: {results.box.mr:.4f}")     # Mean Recall
print(f"mAP@50: {results.box.map50:.4f}")  # Mean Average Precision at IoU 0.5
print(f"mAP@50-95: {results.box.map:.4f}") # Mean Average Precision at IoU 0.5:0.95

"""### Download 'arabic-numbers-2' dataset locally"""

# Zip the 'arabic-numbers-2' dataset
!zip -r /content/arabic_numbers.zip /content/arabic-numbers-2

# Download the zipped file to your local machine
from google.colab import files
files.download('/content/arabic_numbers.zip')

"""# Model To Detect ID Card"""

!pip install roboflow # Already installed, but good for robustness

from roboflow import Roboflow
rf = Roboflow(api_key="JiN3MQkW1CkxFGPpnE0K")
project = rf.workspace("iddetection-zr0sa").project("national-id-ltfb6")
version = project.version(7)
dataset = version.download("yolov8")
print(f"Dataset 'national-id-ltfb6-7' downloaded to: {dataset.location}")
!ls -F {dataset.location}

!yolo task=detect mode=train model=yolov8n.pt data='/content/National-ID-7/data.yaml' epochs=40 imgsz=640 name='train_national_id_v7'

from ultralytics import YOLO

# Load the trained model from the specific run
model = YOLO('/content/runs/detect/train_national_id_v7/weights/best.pt')
# Evaluate on the validation dataset
results = model.val()

# Print summary metrics
print(f"Precision: {results.box.mp:.4f}")  # Mean Precision
print(f"Recall: {results.box.mr:.4f}")     # Mean Recall
print(f"mAP@50: {results.box.map50:.4f}")  # Mean Average Precision at IoU 0.5
print(f"mAP@50-95: {results.box.map:.4f}") # Mean Average Precision at IoU 0.5:0.95

"""### Download 'National-ID-7' dataset locally"""

# Zip the 'National-ID-7' dataset
!zip -r /content/national_id.zip /content/National-ID-7

# Download the zipped file to your local machine
from google.colab import files
files.download('/content/national_id.zip')

! pip install pytesseract

!apt-get update
!apt-get install -y tesseract-ocr
!apt-get install -y tesseract-ocr-ara  # Install Arabic language support

!pip install ultralytics

"""# Import important libraries"""

from ultralytics import YOLO
from IPython.display import display, Image
import cv2
import pytesseract
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
import re
from google.colab import files

"""# Face without rotation

"""

# Function to preprocess the cropped image
def preprocess_image(cropped_image):
    gray = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    return binary

# Functions for specific fields with custom OCR configurations
def extract_text(image, bbox, lang='ara'):
    x1, y1, x2, y2 = bbox
    cropped_image = image[y1:y2, x1:x2]
    preprocessed_image = preprocess_image(cropped_image)
    custom_config = r'--oem 3 --psm 6'
    text = pytesseract.image_to_string(preprocessed_image, lang=lang, config=custom_config)
    return text.strip()

# Function to detect national ID numbers in a cropped image
def detect_national_id(cropped_image):
    model = YOLO('/content/drive/MyDrive/NTI project/Models/detect_id.pt')  # Load the model directly in the function
    results = model(cropped_image)
    detected_info = []

    for result in results:
        for box in result.boxes:
            cls = int(box.cls)
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            detected_info.append((cls, x1))
            cv2.rectangle(cropped_image, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(cropped_image, str(cls), (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36, 255, 12), 2)

    detected_info.sort(key=lambda x: x[1])
    id_number = ''.join([str(cls) for cls, _ in detected_info])

    cv2_imshow(cropped_image)
    return id_number

# Function to remove numbers from a string
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Function to plot image with bounding boxes
def plot_image_with_boxes(image, boxes):
    plt.figure(figsize=(10, 10))
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    ax = plt.gca()
    for box in boxes:
        x1, y1, x2, y2 = [int(coord) for coord in box]
        rect = plt.Rectangle((x1, y1), x2 - x1, y2 - y1, fill=False, color='red', linewidth=2)
        ax.add_patch(rect)
    plt.show()

# Function to expand bounding box height only
def expand_bbox_height(bbox, scale=1.2, image_shape=None):
    x1, y1, x2, y2 = bbox
    width = x2 - x1
    height = y2 - y1
    center_x = x1 + width // 2
    center_y = y1 + height // 2
    new_height = int(height * scale)
    new_y1 = max(center_y - new_height // 2, 0)
    new_y2 = min(center_y + new_height // 2, image_shape[0])
    return [x1, new_y1, x2, new_y2]

# Function to process the cropped image
def process_image(cropped_image):
    # Load the trained YOLO model for objects (fields) detection
    model = YOLO('/content/drive/MyDrive/NTI project/Models/detect_odjects.pt')
    results = model(cropped_image)

    # Variables to store extracted values
    first_name = ''
    second_name = ''
    merged_name = ''
    nid = ''
    address = ''
    serial = ''

    # Loop through the results
    for result in results:
        result.show()  # Shows the image with bounding boxes
        output_path = '/content/d2.jpg'
        result.save(output_path)
        display(Image(filename=output_path))

        boxes = [box.xyxy[0].tolist() for box in result.boxes]
        plot_image_with_boxes(cropped_image, boxes)

        for box in result.boxes:
            bbox = box.xyxy[0].tolist()
            class_id = int(box.cls[0].item())
            class_name = result.names[class_id]
            bbox = [int(coord) for coord in bbox]

            if class_name == 'firstName':
                first_name = extract_text(cropped_image, bbox, lang='ara')
            elif class_name == 'lastName':
                second_name = extract_text(cropped_image, bbox, lang='ara')
            elif class_name == 'serial':
                serial = extract_text(cropped_image, bbox, lang='eng')
            elif class_name == 'address':
                address = extract_text(cropped_image, bbox, lang='ara')
                address = remove_numbers(address)
            elif class_name == 'nid':
                expanded_bbox = expand_bbox_height(bbox, scale=1.5, image_shape=cropped_image.shape)
                cropped_nid = cropped_image[expanded_bbox[1]:expanded_bbox[3], expanded_bbox[0]:expanded_bbox[2]]
                nid = detect_national_id(cropped_nid)

    merged_name = f"{first_name} {second_name}"
    print(f"First Name: {first_name}")
    print(f"Second Name: {second_name}")
    print(f"Full Name: {merged_name}")
    print(f"National ID: {nid}")
    print(f"Address: {address}")
    print(f"Serial: {serial}")

    decoded_info = decode_egyptian_id(nid)
    for key, value in decoded_info.items():
        print(f"{key}: {value}")

# Function to decode the Egyptian ID number
def decode_egyptian_id(id_number):
    governorates = {
        '01': 'Cairo',
        '02': 'Alexandria',
        '03': 'Port Said',
        '04': 'Suez',
        '11': 'Damietta',
        '12': 'Dakahlia',
        '13': 'Ash Sharqia',
        '14': 'Kaliobeya',
        '15': 'Kafr El - Sheikh',
        '16': 'Gharbia',
        '17': 'Monoufia',
        '18': 'El Beheira',
        '19': 'Ismailia',
        '21': 'Giza',
        '22': 'Beni Suef',
        '23': 'Fayoum',
        '24': 'El Menia',
        '25': 'Assiut',
        '26': 'Sohag',
        '27': 'Qena',
        '28': 'Aswan',
        '29': 'Luxor',
        '31': 'Red Sea',
        '32': 'New Valley',
        '33': 'Matrouh',
        '34': 'North Sinai',
        '35': 'South Sinai',
        '88': 'Foreign'
    }

    if len(id_number) != 14:
        raise ValueError("ID number must be 14 digits long")

    century_digit = int(id_number[0])
    year = int(id_number[1:3])
    month = int(id_number[3:5])
    day = int(id_number[5:7])
    governorate_code = id_number[7:9]
    gender_code = int(id_number[12:13])

    if century_digit == 2:
        century = "1900-1999"
        full_year = 1900 + year
    elif century_digit == 3:
        century = "2000-2099"
        full_year = 2000 + year
    else:
        raise ValueError("Invalid century digit")

    gender = "Male" if gender_code % 2 != 0 else "Female"
    governorate = governorates.get(governorate_code, "Unknown")
    birth_date = f"{full_year:04d}-{month:02d}-{day:02d}"

    return {
        'Birth Date': birth_date,
        'Governorate': governorate,
        'Gender': gender
    }

# Function to detect the ID card and pass it to the existing code
def detect_and_process_id_card(image_path):
    # Load the ID card detection model
    id_card_model = YOLO('/content/drive/MyDrive/NTI project/Models/detect_id_card.pt')

    # Perform inference to detect the ID card
    id_card_results = id_card_model(image_path)

    # Load the original image using OpenCV
    image = cv2.imread(image_path)

    # Crop the ID card from the image
    for result in id_card_results:
        for box in result.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])  # Get bounding box coordinates
            cropped_image = image[y1:y2, x1:x2]

    # Pass the cropped image to the existing processing function
    process_image(cropped_image)

# Example usage: Upload an image from your local device
uploaded = files.upload()  # Upload the image

for filename in uploaded.keys():
    detect_and_process_id_card(filename)  # Use the uploaded image

"""### Verify Google Drive Model Paths

Run the following cell to check the contents of your `NTI project/Models` directory in Google Drive. Ensure that the required model files (`detect_id.pt`, `detect_odjects.pt`, and `detect_id_card.pt`) are present there.
"""

import os

model_dir = '/content/drive/MyDrive/NTI project/Models/'

if os.path.exists(model_dir):
    print(f"Contents of {model_dir}:")
    for item in os.listdir(model_dir):
        print(item)
else:
    print(f"Directory not found: {model_dir}")
    print("Please ensure 'NTI project/Models' exists in your Google Drive and is correctly mounted.")

"""### List contents of MyDrive to verify 'NTI project' folder

Run the following cell to see all top-level items in your Google Drive. Look for the exact name of your 'NTI project' folder. If it's different, you'll need to update the `model_dir` path accordingly in the subsequent cells.
"""

import os

drive_root = '/content/drive/MyDrive/'

if os.path.exists(drive_root):
    print(f"Contents of {drive_root}:")
    for item in os.listdir(drive_root):
        print(item)
else:
    print(f"Google Drive root not found: {drive_root}")
    print("Please ensure your Google Drive is mounted correctly.")

"""### Searching for 'NTI project' folder

This cell will recursively search for the 'NTI project' folder within your Google Drive. This might take some time depending on the number of files and folders you have. Please review the output carefully to find the correct path.
"""

import os

def find_folder(root_dir, folder_name):
    for dirpath, dirnames, filenames in os.walk(root_dir):
        if folder_name in dirnames:
            return os.path.join(dirpath, folder_name)
    return None

drive_root = '/content/drive/MyDrive/'
nti_project_folder = find_folder(drive_root, 'NTI project')

if nti_project_folder:
    print(f"'NTI project' folder found at: {nti_project_folder}")
    # You can now update the model_dir variable with this path
    # For example:
    # model_dir = os.path.join(nti_project_folder, 'Models/')
    # print(f"Updated model_dir: {model_dir}")
else:
    print(f"'NTI project' folder not found under {drive_root}")

import os

model_dir = '/content/drive/MyDrive/NTI project/Models/'

# Create the directory if it doesn't exist
os.makedirs(model_dir, exist_ok=True)

print(f"Directory created: {model_dir}")
print("Please upload your model files (detect_id.pt, detect_odjects.pt, detect_id_card.pt) to this directory in your Google Drive.")

"""# Face with rotation

"""

import cv2
import pytesseract
from ultralytics import YOLO
from IPython.display import Image, display
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
import re
from google.colab import files
from PIL import Image as PILImage
import numpy as np
# Function to preprocess the cropped image
def preprocess_image(cropped_image):
    gray = cv2.cvtColor(cropped_image, cv2.COLOR_BGR2GRAY)
    _, binary = cv2.threshold(gray, 127, 255, cv2.THRESH_BINARY)
    return binary

# Functions for specific fields with custom OCR configurations
def extract_text(image, bbox, lang='ara'):
    x1, y1, x2, y2 = bbox
    cropped_image = image[y1:y2, x1:x2]
    preprocessed_image = preprocess_image(cropped_image)
    custom_config = r'--oem 3 --psm 6'
    text = pytesseract.image_to_string(preprocessed_image, lang=lang, config=custom_config)
    return text.strip()

# Function to detect national ID numbers in a cropped image
def detect_national_id(cropped_image):
    model = YOLO('/content/drive/MyDrive/NTI project/Models/detect_id.pt')  # Load the model directly in the function
    results = model(cropped_image)
    detected_info = []

    for result in results:
        for box in result.boxes:
            cls = int(box.cls)
            x1, y1, x2, y2 = map(int, box.xyxy[0])
            detected_info.append((cls, x1))
            cv2.rectangle(cropped_image, (x1, y1), (x2, y2), (0, 255, 0), 2)
            cv2.putText(cropped_image, str(cls), (x1, y1 - 10), cv2.FONT_HERSHEY_SIMPLEX, 0.9, (36, 255, 12), 2)

    detected_info.sort(key=lambda x: x[1])
    id_number = ''.join([str(cls) for cls, _ in detected_info])

    cv2_imshow(cropped_image)
    return id_number

# Function to remove numbers from a string
def remove_numbers(text):
    return re.sub(r'\d+', '', text)

# Function to plot image with bounding boxes
def plot_image_with_boxes(image, boxes):
    plt.figure(figsize=(10, 10))
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    ax = plt.gca()
    for box in boxes:
        x1, y1, x2, y2 = [int(coord) for coord in box]
        rect = plt.Rectangle((x1, y1), x2 - x1, y2 - y1, fill=False, color='red', linewidth=2)
        ax.add_patch(rect)
    plt.show()

# Function to expand bounding box height only
def expand_bbox_height(bbox, scale=1.2, image_shape=None):
    x1, y1, x2, y2 = bbox
    width = x2 - x1
    height = y2 - y1
    center_x = x1 + width // 2
    center_y = y1 + height // 2
    new_height = int(height * scale)
    new_y1 = max(center_y - new_height // 2, 0)
    new_y2 = min(center_y + new_height // 2, image_shape[0])
    return [x1, new_y1, x2, new_y2]

# Function to process the cropped image
def process_image(cropped_image):
    # Load the trained YOLO model for objects (fields) detection
    model = YOLO('/content/drive/MyDrive/NTI project/Models/detect_odjects.pt')
    results = model(cropped_image)

    # Variables to store extracted values
    first_name = ''
    second_name = ''
    merged_name = ''
    nid = ''
    address = ''
    serial = ''

    # Loop through the results
    for result in results:
        result.show()  # Shows the image with bounding boxes
        output_path = '/content/d2.jpg'
        result.save(output_path)
        display(Image(filename=output_path))

        boxes = [box.xyxy[0].tolist() for box in result.boxes]
        plot_image_with_boxes(cropped_image, boxes)

        for box in result.boxes:
            bbox = box.xyxy[0].tolist()
            class_id = int(box.cls[0].item())
            class_name = result.names[class_id]
            bbox = [int(coord) for coord in bbox]

            if class_name == 'firstName':
                first_name = extract_text(cropped_image, bbox, lang='ara')
            elif class_name == 'lastName':
                second_name = extract_text(cropped_image, bbox, lang='ara')
            elif class_name == 'serial':
                serial = extract_text(cropped_image, bbox, lang='eng')
            elif class_name == 'address':
                address = extract_text(cropped_image, bbox, lang='ara')
                address = remove_numbers(address)
            elif class_name == 'nid':
                expanded_bbox = expand_bbox_height(bbox, scale=1.5, image_shape=cropped_image.shape)
                cropped_nid = cropped_image[expanded_bbox[1]:expanded_bbox[3], expanded_bbox[0]:expanded_bbox[2]]
                nid = detect_national_id(cropped_nid)

    merged_name = f"{first_name} {second_name}"
    print(f"First Name: {first_name}")
    print(f"Second Name: {second_name}")
    print(f"Full Name: {merged_name}")
    print(f"National ID: {nid}")
    print(f"Address: {address}")
    print(f"Serial: {serial}")

    decoded_info = decode_egyptian_id(nid)
    for key, value in decoded_info.items():
        print(f"{key}: {value}")

# Function to decode the Egyptian ID number
def decode_egyptian_id(id_number):
    governorates = {
        '01': 'Cairo',
        '02': 'Alexandria',
        '03': 'Port Said',
        '04': 'Suez',
        '11': 'Damietta',
        '12': 'Dakahlia',
        '13': 'Ash Sharqia',
        '14': 'Kaliobeya',
        '15': 'Kafr El - Sheikh',
        '16': 'Gharbia',
        '17': 'Monoufia',
        '18': 'El Beheira',
        '19': 'Ismailia',
        '21': 'Giza',
        '22': 'Beni Suef',
        '23': 'Fayoum',
        '24': 'El Menia',
        '25': 'Assiut',
        '26': 'Sohag',
        '27': 'Qena',
        '28': 'Aswan',
        '29': 'Luxor',
        '31': 'Red Sea',
        '32': 'New Valley',
        '33': 'Matrouh',
        '34': 'North Sinai',
        '35': 'South Sinai',
        '88': 'Foreign'
    }

    if len(id_number) != 14:
        raise ValueError("ID number must be 14 digits long")

    century_digit = int(id_number[0])
    year = int(id_number[1:3])
    month = int(id_number[3:5])
    day = int(id_number[5:7])
    governorate_code = id_number[7:9]
    gender_code = int(id_number[12:13])

    if century_digit == 2:
        century = "1900-1999"
        full_year = 1900 + year
    elif century_digit == 3:
        century = "2000-2099"
        full_year = 2000 + year
    else:
        raise ValueError("Invalid century digit")

    gender = "Male" if gender_code % 2 != 0 else "Female"
    governorate = governorates.get(governorate_code, "Unknown")
    birth_date = f"{full_year:04d}-{month:02d}-{day:02d}"

    return {
        'Birth Date': birth_date,
        'Governorate': governorate,
        'Gender': gender
    }

# Function to process image rotation before further processing
def process_detected_image(image_path):
    # Load the trained model
    model = YOLO('/content/drive/MyDrive/NTI project/Models/detect_id_card.pt')

    # Perform inference on the image
    results = model(image_path)

    # Load the original image using OpenCV
    img = PILImage.open(image_path)

    # Initialize variable for rotated image
    rotated_img = img.copy()  # Make a copy of the image

    # Loop through the results
    for result in results:
        # Loop through the detected objects
        for box in result.boxes:
            # Get the class name
            class_name = result.names[box.cls[0].item()]
            print(f"Detected Class: {class_name}")

            # Rotate the image based on the class name
            if class_name == "front-right":
                rotated_img = img.rotate(-90, expand=True)  # Rotate 90 degrees to the right
                print(f"Rotated image 90 degrees to the right for class: {class_name}")
            elif class_name == "front-left":
                rotated_img = img.rotate(90, expand=True)  # Rotate 90 degrees to the left
                print(f"Rotated image 90 degrees to the left for class: {class_name}")
            elif class_name == "front-bottom":
                rotated_img = img.rotate(180, expand=True)  # Rotate 180 degrees
                print(f"Rotated image 180 degrees for class: {class_name}")
            elif class_name == "front-up":
                rotated_img = img.rotate(0, expand=True)  # Rotate 0 degrees
                print(f"image doesn't need to rotate: {class_name}")

    # Convert the PIL image back to OpenCV format
    rotated_image_cv2 = cv2.cvtColor(np.array(rotated_img), cv2.COLOR_RGB2BGR)

    # Display the rotated image
    display(rotated_img)

    return rotated_image_cv2

# Function to detect the ID card and pass it to the existing code
def detect_and_process_id_card(image_path):
    # Process the detected image for rotation
    rotated_image = process_detected_image(image_path)

    # Crop the ID card from the rotated image
    id_card_model = YOLO('/content/drive/MyDrive/NTI project/Models/detect_id_card.pt')
    id_card_results = id_card_model(rotated_image)

    # Load the original image using OpenCV
    for result in id_card_results:
        for box in result.boxes:
            x1, y1, x2, y2 = map(int, box.xyxy[0])  # Get bounding box coordinates
            cropped_image = rotated_image[y1:y2, x1:x2]

    # Pass the cropped image to the existing processing function
    process_image(cropped_image)

# Example usage: Upload an image from your local device
uploaded = files.upload()  # Upload the image

for filename in uploaded.keys():
    detect_and_process_id_card(filename)  # Use the uploaded image

"""# Back"""

import cv2
import pytesseract
from ultralytics import YOLO
from IPython.display import Image, display
import matplotlib.pyplot as plt
from google.colab.patches import cv2_imshow
from google.colab import files

# Upload file
uploaded = files.upload()
image_path = next(iter(uploaded))  # Get the filename of the uploaded file

# Load the YOLO models
model_id_card = YOLO('/content/drive/MyDrive/NTI project/Models/detect_id_card.pt')  # Model for detecting ID cards
model_job = YOLO('/content/drive/MyDrive/NTI project/Models/detect_odjects.pt')  # Model for extracting job field

# Function to extract text using Tesseract OCR
def extract_text(image, bbox, lang='ara'):
    x1, y1, x2, y2 = bbox
    cropped_image = image[y1:y2, x1:x2]

    # Visualize the cropped region to verify it covers the correct area
    cv2_imshow(cropped_image)

    custom_config = r'--oem 3 --psm 6'
    text = pytesseract.image_to_string(cropped_image, lang=lang, config=custom_config)
    return text.strip()

# Function to plot image with bounding boxes
def plot_image_with_boxes(image, boxes):
    plt.figure(figsize=(10, 10))
    plt.imshow(cv2.cvtColor(image, cv2.COLOR_BGR2RGB))
    ax = plt.gca()
    for box in boxes:
        x1, y1, x2, y2 = [int(coord) for coord in box]
        rect = plt.Rectangle((x1, y1), x2 - x1, y2 - y1, fill=False, color='red', linewidth=2)
        ax.add_patch(rect)
    plt.show()

# Function to detect ID card using the ID card detection model
def detect_id_card(image_path, model):
    results = model(image_path)
    image = cv2.imread(image_path)

    id_card_bboxes = []
    for result in results:
        # Extract bounding boxes
        id_card_bboxes.extend([box.xyxy[0].tolist() for box in result.boxes])

    return image, id_card_bboxes

# Function to process ID card image and extract job field
def process_image(image_path, model_id_card, model_job):
    # Detect ID card
    image, id_card_bboxes = detect_id_card(image_path, model_id_card)

    # Assuming only one ID card detected, process the first one
    if id_card_bboxes:
        bbox = id_card_bboxes[0]  # Get the first detected ID card bbox

        # Crop the ID card region
        x1, y1, x2, y2 = [int(coord) for coord in bbox]
        id_card_image = image[y1:y2, x1:x2]

        # Use the cropped ID card image as input for the job detection model
        results = model_job(id_card_image)  # Pass the cropped image directly

        # Loop through the results
        job = ''
        for result in results:
            # Display the results
            result.show()  # Shows the image with bounding boxes

            # Save the output image
            output_path = '/content/job_output.jpg'
            result.save(output_path)

            # Visualize the saved output image
            display(Image(filename=output_path))

            # Extract bounding boxes and class names
            boxes = [box.xyxy[0].tolist() for box in result.boxes]
            plot_image_with_boxes(id_card_image, boxes)  # Use id_card_image for plotting

            # Extract text for the "job" field
            for box in result.boxes:
                bbox = box.xyxy[0].tolist()  # Get bounding box coordinates
                class_id = int(box.cls[0].item())  # Get class ID
                class_name = result.names[class_id]  # Get class name

                # Convert bounding box coordinates to integers
                bbox = [int(coord) for coord in bbox]

                if class_name == 'job':
                    job = extract_text(id_card_image, bbox, lang='ara')

        # Print the extracted value
        print(f"Job: {job}")
    else:
        print("No ID card detected")

# Call the function to process the image
process_image(image_path, model_id_card, model_job)

"""### Download 'Egyptian-ID-Detectr-3' dataset locally"""

# Zip the 'Egyptian-ID-Detectr-3' dataset
!zip -r /content/egyptian_id_detectr.zip /content/Egyptian-ID-Detectr-3

# Download the zipped file to your local machine
from google.colab import files
files.download('/content/egyptian_id_detectr.zip')

"""### Download 'arabic-numbers-2' dataset locally"""

# Zip the 'arabic-numbers-2' dataset
!zip -r /content/arabic_numbers.zip /content/arabic-numbers-2

# Download the zipped file to your local machine
from google.colab import files
files.download('/content/arabic_numbers.zip')

"""### Download 'National-ID-7' dataset locally"""

# Zip the 'National-ID-7' dataset
!zip -r /content/national_id.zip /content/National-ID-7

# Download the zipped file to your local machine
from google.colab import files
files.download('/content/national_id.zip')

# Verify the contents of the /content/ directory
print("Contents of /content/:")
!ls -F /content/